In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go

## Data loading

In [2]:
nvidia_stock = pd.read_csv("../data/data_stooq/daily/us/nasdaq stocks/2/nvda.us.txt")
nvidia_stock.head(2)

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>,<OPENINT>
0,NVDA.US,D,19990122,0,0.040127,0.044710,0.035533,0.037602,740416863,0
1,NVDA.US,D,19990125,0,0.040586,0.041963,0.037602,0.041499,139413824,0

## Data preprocessing

In [3]:
rename_dict = {}
for col in nvidia_stock.columns:
    rename_dict[col] = col.strip("<>")
    
# display(rename_dict)
nvidia_stock = nvidia_stock.rename(columns = rename_dict)

In [4]:
display(nvidia_stock.describe())

,DATE,TIME,OPEN,HIGH,LOW,CLOSE,VOL,OPENINT
count,6.811000e+03,6811.0,6811.000000,6811.000000,6811.000000,6811.000000,6.811000e+03,6811.0
mean,2.012162e+07,0.0,14.436621,14.676141,14.167586,14.431917,5.857765e+08,0.0
std,7.813449e+04,0.0,37.609916,38.175502,36.939113,37.573813,4.574908e+08,0.0
min,1.999012e+07,0.0,0.032098,0.032555,0.030488,0.031183,0.000000e+00,0.0
25%,2.005103e+07,0.0,0.263716,0.270986,0.255972,0.264006,3.053746e+08,0.0
50%,2.012080e+07,0.0,0.450557,0.457907,0.444376,0.451985,4.929237e+08,0.0
75%,2.019051e+07,0.0,5.734600,5.863495,5.630960,5.742580,7.388232e+08,0.0
max,2.026022e+07,0.0,208.080000,212.189900,205.560000,207.040000,1.010277e+10,0.0

In [5]:
# DROPING OPENINT COLUMN
nvidia_stock = nvidia_stock.drop(columns=["OPENINT"])

In [6]:
nvidia_stock.head(2)

,TICKER,PER,DATE,TIME,OPEN,HIGH,LOW,CLOSE,VOL
0,NVDA.US,D,19990122,0,0.040127,0.044710,0.035533,0.037602,740416863
1,NVDA.US,D,19990125,0,0.040586,0.041963,0.037602,0.041499,139413824

In [7]:
nvidia_stock["DATE"] = pd.to_datetime(nvidia_stock["DATE"], format="%Y%m%d")
print(nvidia_stock['DATE'].min())
print(nvidia_stock['DATE'].max())

1999-01-22 00:00:00
2026-02-20 00:00:00

In [8]:
nvidia_stock.head(2)

,TICKER,PER,DATE,TIME,OPEN,HIGH,LOW,CLOSE,VOL
0,NVDA.US,D,1999-01-22,0,0.040127,0.044710,0.035533,0.037602,740416863
1,NVDA.US,D,1999-01-25,0,0.040586,0.041963,0.037602,0.041499,139413824

In [9]:
fig = go.Figure(data = [go.Candlestick(x=nvidia_stock['DATE'],
                        open = nvidia_stock['OPEN'],
                        high = nvidia_stock['HIGH'],
                        low = nvidia_stock['LOW'],
                        close = nvidia_stock['CLOSE'])])

fig.update_layout(
    title = dict(text = 'Ticker plot for nvidia')
)
fig.show()

## Calculating log return

In [10]:
nvidia_stock["LOG_CLOSE_RETURN"] = np.log(nvidia_stock["CLOSE"] / nvidia_stock["CLOSE"].shift(1))
nvidia_stock["PCT_CLOSE_CHANGE"] = nvidia_stock["CLOSE"].pct_change() * 100
nvidia_stock.head()

,TICKER,PER,DATE,TIME,OPEN,HIGH,LOW,CLOSE,VOL,LOG_CLOSE_RETURN,PCT_CLOSE_CHANGE
0,NVDA.US,D,1999-01-22,0,0.040127,0.044710,0.035533,0.037602,740416863,NaN,NaN
1,NVDA.US,D,1999-01-25,0,0.040586,0.041963,0.037602,0.041499,139413824,0.098620,10.364663
2,NVDA.US,D,1999-01-26,0,0.041963,0.042876,0.037839,0.038287,93919355,-0.080567,-7.740650
3,NVDA.US,D,1999-01-27,0,0.038512,0.039433,0.036230,0.038287,67279765,0.000000,0.000000
4,NVDA.US,D,1999-01-28,0,0.038287,0.038512,0.037839,0.038058,62320835,-0.005986,-0.596811

In [11]:
# plt.figure(figsize=(8, 4))
# plt.plot(nvidia_stock['DATE'], nvidia_stock['LOG_CLOSE_RETURN'])
# plt.show()

fig = go.Figure()
fig.add_trace(go.Scatter(x = nvidia_stock['DATE'], y =nvidia_stock['LOG_CLOSE_RETURN']))
fig.update_layout(
    title = dict(text = "Log Return plot for nvidia")
)
fig.show()

In [12]:
fig = go.Figure()
fig.add_trace(go.Scatter(x = nvidia_stock['DATE'], y =nvidia_stock['PCT_CLOSE_CHANGE']))
fig.update_layout(
    title = dict(text = "Log Return plot for nvidia")
)
fig.show()

In [13]:
nvidia_stock.describe()

,DATE,TIME,OPEN,HIGH,LOW,CLOSE,VOL,LOG_CLOSE_RETURN,PCT_CLOSE_CHANGE
count,6811,6811.0,6811.000000,6811.000000,6811.000000,6811.000000,6.811000e+03,6810.000000,6810.000000
mean,2012-08-05 11:04:55.463221,0.0,14.436621,14.676141,14.167586,14.431917,5.857765e+08,0.001252,0.195172
min,1999-01-22 00:00:00,0.0,0.032098,0.032555,0.030488,0.031183,0.000000e+00,-0.434794,-35.260200
25%,2005-10-29 12:00:00,0.0,0.263716,0.270986,0.255972,0.264006,3.053746e+08,-0.016189,-1.605860
50%,2012-08-03 00:00:00,0.0,0.450557,0.457907,0.444376,0.451985,4.929237e+08,0.001310,0.131043
75%,2019-05-13 12:00:00,0.0,5.734600,5.863495,5.630960,5.742580,7.388232e+08,0.018125,1.829000
max,2026-02-20 00:00:00,0.0,208.080000,212.189900,205.560000,207.040000,1.010277e+10,0.354138,42.495209
std,NaN,0.0,37.609916,38.175502,36.939113,37.573813,4.574908e+08,0.037367,3.752660

In [14]:
total_log_return = nvidia_stock['LOG_CLOSE_RETURN'].sum()
total_growth_multiple = np.exp(total_log_return)
print(f"NVDA grew by a factor of {total_growth_multiple:.1f}x over the period")

print(nvidia_stock['CLOSE'].iloc[0])
print(nvidia_stock['CLOSE'].iloc[-1])
print(nvidia_stock['CLOSE'].iloc[-1]/nvidia_stock['CLOSE'].iloc[0])

# Annualized geometric daily return
n_days = nvidia_stock['LOG_CLOSE_RETURN'].count()
annualized_daily_geometric_return = np.exp(total_log_return / n_days) - 1
print(f"True (geometric) average daily return: {annualized_daily_geometric_return*100:.4f}%")

NVDA grew by a factor of 5048.2x over the period
0.0376018
189.82
5048.162587961215
True (geometric) average daily return: 0.1253%